---
- name: Add SSH access to default security group
  os_security_group_rule:
    security_group: default
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Allow ping for default security group
  os_security_group_rule:
    security_group: default
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- name: Create loadbalancer security group
  os_security_group:
    name: loadbalancer
    state: present

- name: Create webserver security group
  os_security_group:
    name: webserver
    state: present

- name: Allow http traffic for loadbalancer
  os_security_group_rule:
    security_group: loadbalancer
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

- name: Allow http traffic for webserver from loadbalancer
  os_security_group_rule:
    security_group: webserver
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_group: loadbalancer

- name: Create SSH key
  os_keypair:
    name: demo_key
    public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
